### ISSUE TITLE
Does not work with 2.81 update

### ISSUE THREAD

**Issue by bensissel** [kmammou/v-hacd#72]
Will there be an update for this tool to work with blender 2.81? 

getting this error when I try to run it:

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\object_vhacd.py", line 366, in execute
    row = col.row()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.import_scene.x3d" error, could not be found

location: <unknown location>:-1

**Comment by bensissel** [comment]
nevermind - just had to have the x3d plugin enabled.
